# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# Copied from https://github.com/mCodingLLC/pre-commit-example-project/blob/master/.pre-commit-config.yaml
# and modified by K.Chung

repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args: [--line-length=88]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
        language_version: python3

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports
        entry: env SETUPTOOLS_USE_DISTUTILS=stdlib reorder-python-imports

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py39-plus]
